# 2.3 线性代数

## 2.3.1 标量（仅包含一个数值被称为标量）

In [2]:
import torch
from matplotlib.pyplot import axis

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x - y, x * y, x / y, x ** y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 向量（标量组成的列表）

- 标量值称为向量的元素
- 通过一维张量表示向量

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
# 向量的长度
len(x), x.shape

(4, torch.Size([4]))

## 2.3.3 矩阵
- 矩阵是由多个向量组成的列表

In [6]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
# 矩阵的转置
A.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

## 2.3.6 降维

In [8]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [12]:
# 沿着某条轴计算和
A_sum_axis0 = A.sum(dim=0)
A_sum_axis1 = A.sum(dim=1)

print(A)

print(A_sum_axis0)
print(A_sum_axis1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([12, 15, 18])
tensor([ 6, 15, 24])


## 2.3.7 非降维求和

In [13]:
print(A)

sum_A = A.sum(axis=1, keepdim=True)
print(sum_A)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 6],
        [15],
        [24]])


## 2.3.8 点积

In [14]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))