<a href="https://colab.research.google.com/github/Saitama-97/d2l/blob/main/chap2_preliminaries/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 数据操作

## 2.1.1 pytorch

In [15]:
# 导入torch
import torch

# 具有一个轴的张量对应数学中的向量
# 具有两个轴的张量对应数学中的矩阵

# 创建一个张量（行向量）,其中有12个元素
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# 可以通过张量的shape属性查看张量的形状
x.shape

torch.Size([12])

In [17]:
# 如果只想知道张量的元素总数(形状的所有元素乘积)
x.numel()

12

In [18]:
# 可以通过reshape改变张量的形状
y = torch.arange(12).reshape(3,4)
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
y.shape

torch.Size([3, 4])

In [20]:
# 可以不完全指定张量的形状，用-1要求自动计算
z1 = torch.arange(12).reshape(-1,6)  # ?行6列
z2 = torch.arange(12).reshape(3,-1)  # 3行?列
print(z1)
print(z2)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [21]:
# 使用全0、全1、其他常量，快速初始化
t1 = torch.zeros(3,4)
t2 = torch.ones(3,4)
print(t1)
print(t2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
# 随机初始化
t3 = torch.randn(3,4)
print(t3)

tensor([[ 0.4723,  0.8720,  0.8467,  0.0388],
        [-0.6530, -1.9886,  0.2840,  0.7212],
        [ 1.1850, -1.1115, -0.3506,  0.6072]])


In [23]:
# 使用Python list来初始化
t3 = torch.tensor([
    [2,1,3,4],
    [1,3,4,2],
    [3,4,2,1]
])
print(t3)

tensor([[2, 1, 3, 4],
        [1, 3, 4, 2],
        [3, 4, 2, 1]])
