<a href="https://colab.research.google.com/github/Saitama-97/d2l/blob/main/chap2_preliminaries/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 数据操作

## 2.1.1 pytorch

In [63]:
# 导入torch
import torch

# 具有一个轴的张量对应数学中的向量
# 具有两个轴的张量对应数学中的矩阵

# 创建一个张量（行向量）,其中有12个元素
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
# 可以通过张量的shape属性查看张量的形状
x.shape

torch.Size([12])

In [65]:
# 如果只想知道张量的元素总数(形状的所有元素乘积)
x.numel()

12

In [66]:
# 可以通过reshape改变张量的形状
y = torch.arange(12).reshape(3,4)
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [67]:
y.shape

torch.Size([3, 4])

In [68]:
# 可以不完全指定张量的形状，用-1要求自动计算
z1 = torch.arange(12).reshape(-1,6)  # ?行6列
z2 = torch.arange(12).reshape(3,-1)  # 3行?列
print(z1)
print(z2)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [69]:
# 使用全0、全1、其他常量，快速初始化
t1 = torch.zeros(3,4)
t2 = torch.ones(3,4)
print(t1)
print(t2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [70]:
# 随机初始化
t3 = torch.randn(3,4)
print(t3)

tensor([[ 0.1887,  0.4821,  0.9948,  0.4656],
        [ 1.1314,  0.8482, -0.0334,  0.3312],
        [-0.9590,  0.5136,  0.7269,  1.5409]])


In [71]:
# 使用Python list来初始化
t3 = torch.tensor([
    [2,1,3,4],
    [1,3,4,2],
    [3,4,2,1]
])
print(t3)

tensor([[2, 1, 3, 4],
        [1, 3, 4, 2],
        [3, 4, 2, 1]])


## 2.1.2 运算符

- 按元素（elementwise）运算
	- 对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算

In [72]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y, torch.exp(x)  # **运算符是求幂运算 / exp为求幂

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

- 连结（concatenate）操作
	- 沿行（轴-0，形状的第一个元素）
    - 沿列（轴-1，形状的第二个元素）

In [73]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 3, 4, 2],
    [3, 4, 2, 1]
])
print(X)
print(Y)
print(torch.cat((X, Y), dim=0))  # 按行连结
print(torch.cat((X, Y), dim=1))  # 按列连结

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 3., 4., 2.],
        [3., 4., 2., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  3.,  4.,  2.],
        [ 3.,  4.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  3.,  4.,  2.],
        [ 8.,  9., 10., 11.,  3.,  4.,  2.,  1.]])


In [74]:
# 判断两个张量是否对应位置相等
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [75]:
# 对张量的所有元素进行求和
X.sum()

tensor(66.)

## 2.1.3 广播机制

- 正如上面所说，如果两个张量的形状相同，运算是按元素操作（elementwise）
- 如果两个张量的形状不同，也可以进行计算，不过是使用**广播机制**
	- 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
    - 对生成的数组执行按元素操作

In [76]:
# 通常是沿着数组中长度为 1 的轴进行广播
a = torch.arange(3).reshape(3, 1)
b = torch.arange(3).reshape(1, 3)
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]),
 tensor([[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]]))

## 2.1.4 索引和切片

In [77]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [78]:
# 为多个元素赋相同值
X[-1, :] = 8
X

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.],
        [8., 8., 8., 8.]])

## 2.1.5 节省内存

- 运行一些操作可能会导致为新结果分配内存。
	- 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [79]:
# 举例
before = id(Y)
Y = Y + X
id(Y) == before  # 可以看到这里分配了新的内存地址

False

- 使用切片来执行原地操作

In [80]:
# 对比上面的结果
before = id(Y)
Y[:] = Y + X
id(Y) == before  # 可以看到这里并没有分配新的内存地址

True

In [81]:
# 另一种方法
before = id(Y)
Y += X
id(Y) == before

True

## 2.1.6 转换为其他Python对象

In [82]:
t = torch.tensor([1,2,3,4])
A = t.numpy()  # 将 torch 张量转换成 numpy 数组
B = torch.tensor(A)  # 将 numpy 数组转换成 torch 张量
type(A), type(B)

(numpy.ndarray, torch.Tensor)

- torch 张量和 numpy 数组**共享底层内存**，即修改一个张量，也会同时修改另一个张量（见下面示例）

In [83]:
C = torch.tensor([2,2,2,2])
B += C
A, t, B, C

(array([1, 2, 3, 4]),
 tensor([1, 2, 3, 4]),
 tensor([3, 4, 5, 6]),
 tensor([2, 2, 2, 2]))

- 将 torch 张量转换成 Python 标量（item函数或Python的内置函数）

In [84]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)